services:
  db:
    image: mysql
    env_file:
      - .env
    ports:
      - $DBPORT:$DBPORT
    volumes:
      - db-data:/var/lib/mysql

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - 3000:3000

volumes:
  db-data:
